In [2]:
# Import necessary libraries
import pandas as pd

# Function to read a Feather file
def read_feather_file(file_path):
    try:
        # Read the feather file
        df = pd.read_feather(file_path)
        return df
    except Exception as e:
        print(f"An error occurred: {e}")
        return None

# File paths 
# telemetry_large_consumers_file = 'telemetry_large_consumers_DCW.feather'
standard_profiles_file = r'D:\raw\standard_profiles_DCW.feather'
customer_attributes_file = r'D:\raw\customer_attributes_DCW.feather'
telemetry_files=r'D:\raw\telemetry_large_consumers_DCW.feather'

# Read the files
# telemetry_large_consumers_df = read_feather_file(telemetry_large_consumers_file)
standard_profiles_df = read_feather_file(standard_profiles_file)
customer_attributes_df = read_feather_file(customer_attributes_file)
telemetry_df=read_feather_file(telemetry_files)

In [100]:
# Initial Exploration
# To understand the basic structure of the datasets, let's print the first few rows of each dataframe
print("Telemetry Large Consumers:")
telemetry_df.head()

Telemetry Large Consumers:

,RND_ID,2023-01-01 00:00,2023-01-01 00:15,2023-01-01 00:30,2023-01-01 00:45,2023-01-01 01:00,2023-01-01 01:15,2023-01-01 01:30,2023-01-01 01:45,2023-01-01 02:00,...,2023-12-31 21:30,2023-12-31 21:45,2023-12-31 22:00,2023-12-31 22:15,2023-12-31 22:30,2023-12-31 22:45,2023-12-31 23:00,2023-12-31 23:15,2023-12-31 23:30,2023-12-31 23:45
0,8423,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,6756,36.0,32.0,32.0,36.0,32.0,36.0,32.0,36.0,32.0,...,35.89,35.43,34.09,33.31,30.57,29.65,32.06,29.13,28.25,27.85
2,1077,0.0,4.0,0.0,4.0,0.0,4.0,0.0,4.0,0.0,...,2.00,1.50,1.50,2.00,1.50,1.50,2.00,1.50,2.00,1.50
3,8061,16.0,8.0,12.0,8.0,12.0,16.0,12.0,12.0,12.0,...,8.40,8.80,8.80,11.00,10.19,9.19,8.80,9.00,11.00,12.40
4,10575,0.0,4.0,0.0,0.0,4.0,0.0,0.0,4.0,0.0,...,6.67,6.66,3.54,1.15,1.10,1.10,1.10,1.10,1.10,1.12

In [11]:
import pandas as pd

# **Assuming you have your 'telemetry_large_consumers_df' loaded as a pandas DataFrame**

# Select the first 100 rows
df_first_100 = telemetry_large_consumers_df.head(100)
# Save as a new feather file
df_first_100.to_feather('telemetry_first_100.feather')

In [3]:
print("\nStandard Profiles:")
standard_profiles_df.head(10)

Standard Profiles:

     DATUM_TIJDSTIP        PROFIEL    WAARDE
0  2023-10-06 07:30   KVKSEGMENT_7  0.000041
1  2023-08-27 14:15   KVKSEGMENT_9  0.000019
2  2023-02-25 18:00  KVKSEGMENT_18  0.000032
3  2023-11-29 00:15  KVKSEGMENT_12  0.000019
4  2023-04-26 17:45   KVKSEGMENT_7  0.000024
5  2023-10-15 22:00   KVKSEGMENT_8  0.000015
6  2023-07-13 17:15   KVKSEGMENT_8  0.000032
7  2023-03-04 11:30  KVKSEGMENT_12  0.000026
8  2023-07-28 07:15   KVKSEGMENT_1  0.000043
9  2023-04-30 22:00  KVKSEGMENT_18  0.000019

In [112]:
print("\nCustomer Attributes:")
customer_attributes_df.head()

Customer Attributes:

   RND_ID BASELOAD_PROFILE AANSLUITCATEGORIE
0    8423              010              AC4A
1    6756              E3B              AC4B
2    1077              008              AC4A
3    8061              001              AC4B
4   10575              008              AC4B

In [91]:
standard_profiles_df['PROFIEL'].unique()

array(['KVKSEGMENT_7', 'KVKSEGMENT_9', 'KVKSEGMENT_18', 'KVKSEGMENT_12',
       'KVKSEGMENT_8', 'KVKSEGMENT_1', 'KVKSEGMENT_15', 'KVKSEGMENT_3',
       'KVKSEGMENT_10', 'KVKSEGMENT_11', 'KVKSEGMENT_20', 'KVKSEGMENT_4',
       'KVKSEGMENT_19', 'KVKSEGMENT_14', 'KVKSEGMENT_17', 'KVKSEGMENT_13',
       'KVKSEGMENT_16', 'PV', 'KVKSEGMENT_5', 'KVKSEGMENT_6',
       'KVKSEGMENT_2', 'WIND_KLEIN'], dtype=object)

In [63]:
pip install googletrans==4.0.0-rc1

Requirement already satisfied: googletrans==4.0.0-rc1 in c:\users\20235624\appdata\local\anaconda3\lib\site-packages (4.0.0rc1)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: httpx==0.13.3 in c:\users\20235624\appdata\local\anaconda3\lib\site-packages (from googletrans==4.0.0-rc1) (0.13.3)
Requirement already satisfied: certifi in c:\users\20235624\appdata\local\anaconda3\lib\site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2023.7.22)
Requirement already satisfied: hstspreload in c:\users\20235624\appdata\local\anaconda3\lib\site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2024.5.1)
Requirement already satisfied: sniffio in c:\users\20235624\appdata\local\anaconda3\lib\site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (1.2.0)
Requirement already satisfied: chardet==3.* in c:\users\20235624\appdata\local\anaconda3\lib\site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (3.0.4)
Requirement already satisfied: idna==2.* in c:\users\20235624\appdata\local\anaconda3\lib\site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2.10)
Requirement already satisfied: rfc3986<2,>=1.3 in c:\users\20235624\appdata\local\anaconda3\lib\site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (1.5.0)
Requirement already satisfied: httpcore==0.9.* in c:\users\20235624\appdata\local\anaconda3\lib\site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (0.9.1)
Requirement already satisfied: h11<0.10,>=0.8 in c:\users\20235624\appdata\local\anaconda3\lib\site-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (0.9.0)
Requirement already satisfied: h2==3.* in c:\users\20235624\appdata\local\anaconda3\lib\site-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (3.2.0)
Requirement already satisfied: hyperframe<6,>=5.2.0 in c:\users\20235624\appdata\local\anaconda3\lib\site-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (5.2.0)
Requirement already satisfied: hpack<4,>=3.0 in c:\users\20235624\appdata\local\anaconda3\lib\site-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (3.0.0)

In [133]:
from googletrans import Translator
standard_profiles_df = read_feather_file(standard_profiles_file)

# Instantiate the translator
translator = Translator()

# Function to translate column names
def translate_column_names(dataframe):
    translations = {col: translator.translate(col, src='nl', dest='en').text for col in dataframe.columns}
    dataframe.rename(columns=translations, inplace=True)
    return dataframe


# Now translate the column names from Dutch to English
standard_profiles_df = translate_column_names(standard_profiles_df)
customer_attributes_df = translate_column_names(customer_attributes_df)

In [93]:
# Print the translated dataframe columns
print(standard_profiles_df.head())

       Date of time        PROFILE     VALUE
0  2023-10-06 07:30   KVKSEGMENT_7  0.000041
1  2023-08-27 14:15   KVKSEGMENT_9  0.000019
2  2023-02-25 18:00  KVKSEGMENT_18  0.000032
3  2023-11-29 00:15  KVKSEGMENT_12  0.000019
4  2023-04-26 17:45   KVKSEGMENT_7  0.000024

In [94]:
df = standard_profiles_df

In [1]:
# Convert 'Date of time' column to datetime format
#df['Date of time'] = pd.to_datetime(df['Date of time'])

# Round the datetime to the nearest day
#df['Date of time'] = df['Date of time'].dt.to_period('Y').dt.to_timestamp()

# Group by 'PROFILE' and sum the 'VALUE' column
#grouped_df = df.groupby(['PROFILE', 'Date of time']).sum().reset_index()

#print(grouped_df)

In [97]:
df['Date of time'] = pd.to_datetime(df['Date of time'])
grouped_data = df.groupby(['Date of time', 'PROFILE'])['VALUE'].apply(list).unstack()

grouped_data.head()

PROFILE,KVKSEGMENT_1,KVKSEGMENT_10,KVKSEGMENT_11,KVKSEGMENT_12,KVKSEGMENT_13,KVKSEGMENT_14,KVKSEGMENT_15,KVKSEGMENT_16,KVKSEGMENT_17,KVKSEGMENT_18,...,KVKSEGMENT_20,KVKSEGMENT_3,KVKSEGMENT_4,KVKSEGMENT_5,KVKSEGMENT_6,KVKSEGMENT_7,KVKSEGMENT_8,KVKSEGMENT_9,PV,WIND_KLEIN
Date of time,,,,,,,,,,,,,,,,,,,,,
2023-01-01 00:00:00,[1.58346704490639e-05],[1.81751848381549e-05],[2.37185829316073e-05],[1.70338571998236e-05],[1.92805556962131e-05],[1.58110406348387e-05],[1.75181644194428e-05],[4.37118211521283e-05],[1.42484905768051e-05],[2.04064878801877e-05],...,[1.55885548184902e-05],[1.95865875224097e-05],[1.19576279276147e-05],[2.37783193058941e-05],[3.72574454355318e-05],[1.42444255310037e-05],[1.56949113765306e-05],[1.40776843587934e-05],[0.0],[-0.6588831]
2023-01-01 00:15:00,[1.36119115623519e-05],[1.70945436329815e-05],[2.50079526137988e-05],[1.62603451959799e-05],[1.88371085567072e-05],[1.67685679489908e-05],[1.78659533394132e-05],[3.85135434889168e-05],[1.38770752040456e-05],[2.04456705554758e-05],...,[1.70465283569563e-05],[2.33904217263225e-05],[1.10529851554768e-05],[2.54732771234116e-05],[3.65028956412962e-05],[1.60660895958633e-05],[1.49445880380991e-05],[1.31196892150853e-05],[0.0],[-0.8097361]
2023-01-01 00:30:00,[1.40551480379954e-05],[1.77310133873813e-05],[2.36900684567921e-05],[1.79861899762202e-05],[1.900954629891e-05],[1.54356271688573e-05],[1.73437756546592e-05],[4.20008414935758e-05],[1.37454539011282e-05],[2.10994845551123e-05],...,[1.49355189953038e-05],[1.76242000670815e-05],[1.16415920259228e-05],[2.27049287412906e-05],[3.68013419990633e-05],[1.36906079806196e-05],[1.63819669672624e-05],[1.41362200221633e-05],[0.0],[-0.8408035]
2023-01-01 00:45:00,[1.57880788517131e-05],[1.69149007219553e-05],[2.5173830042745e-05],[1.64812940016876e-05],[1.88935604015072e-05],[1.67118901386632e-05],[1.99907497906628e-05],[3.50252764370826e-05],[1.43214093195388e-05],[2.00581501752157e-05],...,[1.60465117962481e-05],[2.30620341967039e-05],[1.07498292304665e-05],[2.63785714606966e-05],[3.48823004054981e-05],[1.31516281700515e-05],[1.52825310647501e-05],[1.49834447867246e-05],[0.0],[-0.8224287]
2023-01-01 01:00:00,[1.37535771291718e-05],[1.740702204743e-05],[2.42232088622858e-05],[1.69593866070147e-05],[2.03210954902596e-05],[1.54943803743036e-05],[1.64621280929023e-05],[3.73447351979905e-05],[1.41359404078705e-05],[2.00329697907113e-05],...,[1.57428419026847e-05],[1.73582994709882e-05],[1.09325096488206e-05],[2.28111503029264e-05],[3.83975366339591e-05],[1.46737479007946e-05],[1.47981554248382e-05],[1.54883284369451e-05],[0.0],[-0.8203358]

In [96]:
#grouped_data.to_csv(r'C:\Users\20235624\Documents\raw\raw\grouped_data.csv')

### KVK segments are the segments from the chamber of commerce

In [5]:
# Print the translated dataframe columns
print(customer_attributes_df.head())

   Rnd_id Baseload_profile Connection category
0    8423              010                AC4A
1    6756              E3B                AC4B
2    1077              008                AC4A
3    8061              001                AC4B
4   10575              008                AC4B

In [6]:
customer_attributes_df['Baseload_profile'].unique()

array(['010', 'E3B', '008', '001', '013', 'PV', '004', 'E3A', 'E3C',
       '014', '018', '002', '017', '006', 'E3D', '009', '012', '019',
       '016', '007', '015', '020', '005', '011', 'WIND_KLEIN'],
      dtype=object)

In [7]:
customer_attributes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17102 entries, 0 to 17101
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Rnd_id               17102 non-null  int32
 1   Baseload_profile     17102 non-null  object
 2   Connection category  17102 non-null  object
dtypes: int32(1), object(2)
memory usage: 334.2+ KB

In [113]:
telemetry_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17102 entries, 0 to 17101
Columns: 35041 entries, RND_ID to 2023-12-31 23:45
dtypes: float64(35040), object(1)
memory usage: 4.5+ GB

In [41]:
# Categorizing BASELOAD_PROFILE by AANSLUITCATEGORIE, then grouping RND_ID by BASELOAD_PROFILE
categorized_by_connection = customer_attributes_df.groupby(['Baseload_profile','Connection category' ])['Rnd_id'].apply(list).unstack()

# Display the result
categorized_by_connection.head(), categorized_by_connection.shape

(Connection category                                               AC4A  \
 Baseload_profile
 001                  [9284, 826, 12162, 1096, 12819, 3091, 120, 919...
 002                  [9026, 140, 369, 9707, 2616, 6259, 4233, 9512,...
 004                  [5079, 4638, 2001, 6366, 10492, 8422, 64, 94, ...
 005                  [9347, 1042, 9420, 5961, 3266, 3850, 11183, 21...
 006                  [10341, 6300, 4620, 2951, 1519, 12064, 7382, 6...

 Connection category                                               AC4B
 Baseload_profile
 001                  [8061, 8721, 2122, 2585, 1270, 11548, 3845, 65...
 002                  [8040, 11927, 1875, 8902, 89, 4894, 5546, 2888...
 004                  [3627, 5864, 1163, 7302, 3743, 3759, 4209, 888...
 005                  [3217, 11926, 3069, 9688, 11966, 10786, 11035,...
 006                  [11025, 10473, 5581, 10132, 6777, 1891, 5090, ...  ,
 (25, 2))

In [42]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(categorized_by_connection)

Connection category                                               AC4A  \
Baseload_profile
001                  [9284, 826, 12162, 1096, 12819, 3091, 120, 919...
002                  [9026, 140, 369, 9707, 2616, 6259, 4233, 9512,...
004                  [5079, 4638, 2001, 6366, 10492, 8422, 64, 94, ...
005                  [9347, 1042, 9420, 5961, 3266, 3850, 11183, 21...
006                  [10341, 6300, 4620, 2951, 1519, 12064, 7382, 6...
007                  [13240, 5069, 11598, 13036, 12865, 3718, 13005...
008                  [1077, 4797, 3513, 10578, 2023, 7697, 7143, 79...
009                  [5833, 11734, 12267, 6494, 2129, 2196, 12659, ...
010                  [8423, 11160, 2983, 11686, 7067, 3518, 8960, 4...
011                  [7554, 8179, 5015, 13046, 9697, 10095, 12084, ...
012                  [22, 3027, 12948, 2214, 2349, 318, 9788, 4527,...
013                  [8484, 7779, 3549, 1984, 1114, 9794, 11371, 11...
014                  [9944, 932, 2754, 13124, 3916, 9801, 1649, 293...
015                  [9990, 6153, 13230, 6124, 4320, 4479, 12680, 1...
016                  [10722, 7160, 8984, 11788, 5839, 7155, 9249, 6...
017                  [1089, 11337, 7693, 13072, 6088, 1520, 11342, ...
018                  [11466, 6771, 9564, 13177, 5988, 686, 10183, 5...
019                  [11384, 11310, 5714, 5012, 11882, 5904, 11747,...
020                  [11381, 6686, 3133, 8203, 3960, 9342, 440, 471...
E3A                  [7276, 11040, 5177, 30, 4745, 11402, 1449, 114...
E3B                  [339, 282, 7361, 9128, 12641, 7476, 6879, 7384...
E3C                  [1501, 2271, 12050, 2901, 7947, 6371, 783, 754...
E3D                  [5120, 2072, 6052, 1499, 3734, 336, 155, 7576,...
PV                   [2271, 2023, 11384, 9026, 1449, 13240, 11437, ...
WIND_KLEIN           [9347, 1042, 9420, 5961, 3266, 3850, 11183, 21...

Connection category                                               AC4B
Baseload_profile
001                  [8061, 8721, 2122, 2585, 1270, 11548, 3845, 65...
002                  [8040, 11927, 1875, 8902, 89, 4894, 5546, 2888...
004                  [3627, 5864, 1163, 7302, 3743, 3759, 4209, 888...
005                  [3217, 11926, 3069, 9688, 11966, 10786, 11035,...
006                  [11025, 10473, 5581, 10132, 6777, 1891, 5090, ...
007                  [4883, 13129, 3329, 6375, 8768, 7149, 2703, 11...
008                  [10575, 1179, 10507, 5407, 904, 8802, 12125, 9...
009                  [12893, 747, 2071, 4318, 12099, 5183, 11710, 7...
010                  [2389, 2208, 6598, 13227, 3558, 12699, 4047, 2...
011                  [10426, 11113, 9840, 4118, 1852, 11072, 5911, ...
012                  [7284, 1280, 5413, 6142, 9845, 11414, 12067, 1...
013                  [4080, 10038, 9741, 303, 13259, 7794, 1750, 79...
014                  [8460, 4342, 879, 12137, 2702, 12925, 8602, 12...
015                  [2707, 7095, 5687, 11553, 9199, 7131, 8946, 18...
016                  [2074, 641, 1294, 5807, 2502, 9306, 7986, 2194...
017                  [8183, 13006, 1784, 663, 7099, 592, 9092, 1151...
018                  [10524, 9065, 10865, 5857, 4394, 9767, 3861, 7...
019                  [5576, 2542, 2029, 7101, 8494, 13285, 12052, 3...
020                  [10182, 5751, 364, 809, 5207, 2935, 333, 2304,...
E3A                  [12200, 10879, 10976, 84, 874, 10344, 4640, 49...
E3B                  [6756, 9476, 457, 2125, 5153, 9815, 5919, 2674...
E3C                  [1860, 9805, 4961, 4531, 810, 8643, 6696, 4984...
E3D                  [8531, 6741, 6197, 10483, 11368, 11642, 9234, ...
PV                   [4080, 5864, 1163, 7302, 457, 10524, 874, 5407...
WIND_KLEIN                  [2715, 4661, 2313, 4668, 3316, 5365, 4583]

In [1]:
#categorized_by_connection.to_csv(r'C:\Users\20235624\Documents\raw\raw\categorized_data.csv')

Telemetry DataFrame ID column type: object

AttributeError: 'DataFrame' object has no attribute 'dtype'

KeyError: 'RND_ID'

,RND_ID,2023-01-01 00:00,2023-01-01 00:15,2023-01-01 00:30,2023-01-01 00:45,2023-01-01 01:00,2023-01-01 01:15,2023-01-01 01:30,2023-01-01 01:45,2023-01-01 02:00,...,2023-12-31 22:30,2023-12-31 22:45,2023-12-31 23:00,2023-12-31 23:15,2023-12-31 23:30,2023-12-31 23:45,Your_ID_Column,BASELOAD_PROFILE,AANSLUITCATEGORIE,Rnd_id
0,8423,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0,...,0.00,0.00,0.00,0.00,0.00,0.00,8423,010,AC4A,8423
1,6756,36.0,32.0,32.0,36.0,32.0,36.0,32.0,36.0,32.0,...,30.57,29.65,32.06,29.13,28.25,27.85,6756,E3B,AC4B,6756
2,1077,0.0,4.0,0.0,4.0,0.0,4.0,0.0,4.0,0.0,...,1.50,1.50,2.00,1.50,2.00,1.50,1077,008,AC4A,1077
3,8061,16.0,8.0,12.0,8.0,12.0,16.0,12.0,12.0,12.0,...,10.19,9.19,8.80,9.00,11.00,12.40,8061,001,AC4B,8061
4,10575,0.0,4.0,0.0,0.0,4.0,0.0,0.0,4.0,0.0,...,1.10,1.10,1.10,1.10,1.10,1.12,10575,008,AC4B,10575

In [131]:

categorized_by_connection1.head(), categorized_by_connection1.shape

KeyError: 'CONNECTION CATEGORY'